name: ChromDMM
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-essentials
  - r-devtools
  - gcc=11.2
  - gxx
  - gfortran
  - r-optparse
  - bioconductor-genomicranges
  - bioconductor-iranges
  - r-egg
  - r-gridextra
  - r-cowplot



