# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bin_signal <- function(data, bin_width) {
    .Call(`_ChromDMM_bin_signal`, data, bin_width)
}

extract_binned_signal <- function(binned, indices) {
    .Call(`_ChromDMM_extract_binned_signal`, binned, indices)
}

disable_gsl_error_handler <- function() {
    invisible(.Call(`_ChromDMM_disable_gsl_error_handler`))
}

soft_kmeans <- function(data, K, verbose = FALSE, randomInit = TRUE, centers = matrix(), stiffness = 50.0, threshold = 1.0e-6, maxIt = 1000L, rowNorm = TRUE) {
    .Call(`_ChromDMM_soft_kmeans`, data, K, verbose, randomInit, centers, stiffness, threshold, maxIt, rowNorm)
}

neg_log_evidence_lambda_pi <- function(lambda, lparams) {
    .Call(`_ChromDMM_neg_log_evidence_lambda_pi`, lambda, lparams)
}

neg_log_derive_evidence_lambda_pi <- function(ptLambda, lparams) {
    .Call(`_ChromDMM_neg_log_derive_evidence_lambda_pi`, ptLambda, lparams)
}

neg_log_evidence_i <- function(dataRow, Lambda, LnGammaLambda0) {
    .Call(`_ChromDMM_neg_log_evidence_i`, dataRow, Lambda, LnGammaLambda0)
}

calc_z <- function(Z, data, W, Lambda) {
    .Call(`_ChromDMM_calc_z`, Z, data, W, Lambda)
}

neg_log_likelihood <- function(W, Lambda, data, eta, nu, etah, nuh) {
    .Call(`_ChromDMM_neg_log_likelihood`, W, Lambda, data, eta, nu, etah, nuh)
}

neg_log_evidence_lambda_pi_shift_flip <- function(lambda, lparams) {
    .Call(`_ChromDMM_neg_log_evidence_lambda_pi_shift_flip`, lambda, lparams)
}

neg_log_derive_evidence_lambda_pi_shift_flip <- function(ptLambda, lparams) {
    .Call(`_ChromDMM_neg_log_derive_evidence_lambda_pi_shift_flip`, ptLambda, lparams)
}

calc_z_shift_flip <- function(Z, data, W, xi, zeta, Lambda) {
    .Call(`_ChromDMM_calc_z_shift_flip`, Z, data, W, xi, zeta, Lambda)
}

neg_log_likelihood_shift_flip <- function(W, xi, zeta, Lambda, data, eta, nu, etah, nuh, S) {
    .Call(`_ChromDMM_neg_log_likelihood_shift_flip`, W, xi, zeta, Lambda, data, eta, nu, etah, nuh, S)
}

neg_log_evidence_lambda_pi_flip <- function(lambda, lparams) {
    .Call(`_ChromDMM_neg_log_evidence_lambda_pi_flip`, lambda, lparams)
}

neg_log_derive_evidence_lambda_pi_flip <- function(ptLambda, lparams) {
    .Call(`_ChromDMM_neg_log_derive_evidence_lambda_pi_flip`, ptLambda, lparams)
}

calc_z_flip <- function(Z, data, W, zeta, Lambda) {
    .Call(`_ChromDMM_calc_z_flip`, Z, data, W, zeta, Lambda)
}

neg_log_likelihood_flip <- function(W, zeta, Lambda, data, eta, nu, etah, nuh) {
    .Call(`_ChromDMM_neg_log_likelihood_flip`, W, zeta, Lambda, data, eta, nu, etah, nuh)
}

neg_log_evidence_lambda_pi_shift <- function(lambda, lparams) {
    .Call(`_ChromDMM_neg_log_evidence_lambda_pi_shift`, lambda, lparams)
}

neg_log_derive_evidence_lambda_pi_shift <- function(ptLambda, lparams) {
    .Call(`_ChromDMM_neg_log_derive_evidence_lambda_pi_shift`, ptLambda, lparams)
}

calc_z_shift <- function(Z, data, W, xi, Lambda) {
    .Call(`_ChromDMM_calc_z_shift`, Z, data, W, xi, Lambda)
}

neg_log_likelihood_shift <- function(W, xi, Lambda, data, eta, nu, etah, nuh, S) {
    .Call(`_ChromDMM_neg_log_likelihood_shift`, W, xi, Lambda, data, eta, nu, etah, nuh, S)
}

kmeanspp_initialize <- function(mat, K) {
    .Call(`_ChromDMM_kmeanspp_initialize`, mat, K)
}

